### ISSUE TITLE
ESP32 reboots permanently

### ISSUE THREAD

**Issue by DirkausHH** [MCeddy/co2-meter-esp32#3]
Hi,

very nice project. After some hassle I'm now able to compile it with PlatfomIO, but the device goes in a reboot loop afterwards.
I adapted the ini to my Lolino32 and currently neither the sensor nor the display is connected, but I can't even reach the AP mode.

The monitor provides the following output:

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
assertion "Invalid mbox" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c", line 416, function: tcpip_api_call
abort() was called at PC 0x40101de3 on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x40089520:0x3ffb1df0 0x4008979d:0x3ffb1e10 0x40101de3:0x3ffb1e30 0x4012927f:0x3ffb1e60 0x400dd637:0x3ffb1e90 0x400e24be:0x3ffb1ee0 0x400d1ba9:0x3ffb1f00 0x400d232c:0x3ffb1f40 0x400e74e2:0x3ffb1fb0 0x4008a7ae:0x3ffb1fd0
  #0  0x40089520:0x3ffb1df0 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #1  0x4008979d:0x3ffb1e10 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
  #2  0x40101de3:0x3ffb1e30 in __assert_func at /Users/ivan/e/newlib_xtensa-2.2.0-bin/newlib_xtensa-2.2.0/xtensa-esp32-elf/newlib/libc/stdlib/../../../.././newlib/libc/stdlib/assert.c:63 (discriminator 8)   
  #3  0x4012927f:0x3ffb1e60 in tcpip_api_call at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:483
  #4  0x400dd637:0x3ffb1e90 in AsyncServer::begin() at .pio\libdeps\esp32dev\AsyncTCP-esphome\src/AsyncTCP.cpp:1074
      (inlined by) AsyncServer::begin() at .pio\libdeps\esp32dev\AsyncTCP-esphome\src/AsyncTCP.cpp:1330
  #5  0x400e24be:0x3ffb1ee0 in AsyncWebServer::begin() at .pio\libdeps\esp32dev\ESPAsyncWebServer-esphome\src/WebServer.cpp:181
  #6  0x400d1ba9:0x3ffb1f00 in setupWebserver() at .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Misc/SafeBoolIdiom.hpp:15
  #7  0x400d232c:0x3ffb1f40 in setup() at .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Misc/SafeBoolIdiom.hpp:15
  #8  0x400e74e2:0x3ffb1fb0 in loopTask(void*) at C:\Users\Dirk\.platformio\packages\framework-arduinoespressif32\cores\esp32/main.cpp:18
  #9  0x4008a7ae:0x3ffb1fd0 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

**Comment by DirkausHH** [comment]
I made the 1.1.3 to work on my device.
The platformio.ini lib_deps must be updated to tobiasschuerg/MH-Z CO2 Sensors @ ~**1.4.0**
Otherwise the build fails.
The current 1.2.0 version still won't boot...

**Comment by coding-lemur** [comment]
Hi Dirk. I'm glad you like my project. :)
I checked the dependencies: In my latest version (1.1.3) I'm already unsing the 1.4.0 version of the CO2 sensor lib. So it should compile. But I'm used the evening to update a few libraries to the current version.

best regards

René
