### ISSUE TITLE
unexpected readings and weird temperature and co2 values

### ISSUE THREAD

**Issue by bbregman** [MCeddy/co2-meter-esp32#4]
hello @coding-lemur , i have followed your instructions to connect all the hardware bits, downloaded the software from github, compiled it into platformio in visualstudio code (needed to change some version numbers for the dependency libs otherwise the project would not compile, gave some errors and warnings) and uploaded the software to the esp32-devkit board. led display is working, co2sensor is blinking red twice a second I think and says:  
- temperature: 0
- co2: -2
- unexpected readings .....

Do you know what is missing for a good reading? 
- is the co2 sensor not working well, or not correctly connected? 
- is the software incorrectly reading or calculating the values?

thanks in advance!

**Comment by coding-lemur** [comment]
Hey @bbregman . Thank you for using my project. The code has some issues with the new library updates :/

The error-code -2 from the co-sensor library indicates that there was no response from the sensor: Maybe the software-serial library has an issue or your wiring isn't correct. Currently I'm not able to upgrade libraries and fix the issues.

Best regards

René

**Comment by bbregman** [comment]
hello @coding-lemur , thank you for your reply. eventually i figured it out by using esphome and resetting the co2 sensor, then the values came in and the software was working. thanks again for your clear documentation, this helped me a lot in building the device and troubleshooting the issue.

**Comment by bbregman** [comment]
i guess this issue can be marked as closed :)
